## Linear Regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from ydata_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('./dataset/Advertising.csv')
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
pf = ProfileReport(df)
# pf.to_widgets()

In [4]:
# pf.to_file('report.html')

In [5]:
x = df[['TV']]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [6]:
y = df.Sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [7]:
# Use LinearRegression for getting straight line 
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(x, y)

LinearRegression()

In [8]:
linear.intercept_

7.032593549127695

In [9]:
linear.coef_

array([0.04753664])

### straight line equation is
sales = m(TV) + c
= 0.0475($10) + 7.0325

In [10]:
file = "linear_reg.sav"
pickle.dump(linear, open(file, 'wb'))

In [11]:
# linear.predict([[45]])
expenses = [4,5,6,7,89,34,45,67,23]
for ex in expenses:
    print(linear.predict([[ex]]))

[7.22274011]
[7.27027675]
[7.31781339]
[7.36535003]
[11.26335455]
[8.64883932]
[9.17174237]
[10.21754846]
[8.12593628]


/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have vali

In [12]:
saved_model = pickle.load(open(file, 'rb'))
saved_model.predict([[45]])

/home/tops/workspace/EDA_Feature_engineering/venv/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.17174237])

In [13]:
linear.score(x,y)

0.611875050850071

In [15]:
# Multiple features
data_x = df[['TV','Radio','Newspaper']]
data_y = df.Sales

In [16]:
lr = LinearRegression()
lr.fit(X=data_x, y=data_y)

LinearRegression()

In [17]:
lr.intercept_

2.938889369459412

In [18]:
lr.coef_ 

array([ 0.04576465,  0.18853002, -0.00103749])

In [19]:
lr.score(X=data_x, y=data_y)

0.8972106381789522